<CampaignScroll>
    scroll_type: ["content", "bars"]
    bar_width: dp(12)
    effect_cls: "ScrollEffect"
    canvas.after:
        Color:
            rgba: (0.82, 0.2, 0, root.border_on)
        Line:
            width: 1.5
            rectangle: self.x+1, self.y+1, self.width-1, self.height-1

<DownloadDataWarningMessage>
    color: (1, 1, 1, 1)
    canvas.before:
        Color:
            rgba: (0xd2/0xff, 0x33/0xff, 0, 1)
        Rectangle:
            pos: (self.x - 8, self.y - 8)
            size: (self.width + 30, self.height + 16)

<MissionSearchInput>:
    hint_text: 'Search...'
    size_hint_y: None
    height: dp(34)
    multiline: False
    write_tab: False
    background_color: 0.15, 0.15, 0.15, 1
    foreground_color: 1, 1, 1, 1
    cursor_color: 1, 1, 1, 1
    hint_text_color: 0.5, 0.5, 0.5, 1
    padding: dp(10), dp(7)

<MultiCampaignLayout>
    cols: 1
    size_hint_y: None
    height: self.minimum_height + 15
    padding: [5,0,dp(12),0]

<CampaignLayout>:
    cols: 1

<MissionLayout>:
    rows: 1

<RegionLayout>:
    cols: 1

<ColumnLayout>:
    rows: 1

<MissionCategory>:
    cols: 1
    spacing: [0,5]

<MissionButton>:
    text_size: self.size
    markup: True
    halign: 'center'
    valign: 'middle'
    padding: [5,0,5,0]
    outline_width: 1
    canvas.before:
        Color:
            rgba: (1, 193/255, 86/255, root.is_goal)
        Line:
            width: 1
            rectangle: (self.x, self.y + 0.5, self.width, self.height)
    canvas.after:
        Color:
            rgba: (0.8, 0.8, 0.8, root.is_exit)
        Line:
            width: 1
            rectangle: (self.x + 2, self.y + 3, self.width - 4, self.height - 4)
        Color:
            rgba: (0, 0, 0, 0.65 * root.is_dimmed)
        Rectangle:
            pos: self.pos
            size: self.size